#!/usr/bin/env python
'''
initial_db
Description#   Initialize a database and test case
Developer#     Thada Wangthammang
'''
import os
import sys
import pymongo
import pprint

from r2als import models
from r2als import config as cf
from r2als.scripts import convert_curriculum as cc

default_categories = ['lecture', 'lab','project']
grade_info = [
    {'name': "A", 'score': 4.0},
    {'name': "B+", 'score': 3.5},
    {'name': "B", 'score': 3.0},
    {'name': "C+", 'score': 2.5},
    {'name': "C", 'score': 2.0},
    {'name': "D+", 'score': 1.5},
    {'name': "D", 'score': 1.0},
    {'name': "E", 'score': 0.0},
    {'name': "S"},
    {'name': "U"},
    {'name': "W"}
]
# curriculum_data = {
#     'faculty': 'Engineering',
#     'department': 'Computer Engineering',
#     'year': 2553
# }

# Not check key yet
raw_curriculum = cc.CsvToModel().process('../data/coe_2553_curriculum.csv', True)
raw_subjects = raw_curriculum['subjects']
curriculum_data = raw_curriculum['info']

pp = pprint.PrettyPrinter(indent=4)
# pp.pprint(raw_subjects )


if __name__ == '__main__':
    # if len(argv) != 2:
    #     usage(argv)
    # config_uri = argv[1]
    # setup_logging(config_uri)
    # settings = get_appsettings(config_uri)

    models.initial({'mongodb.db_name':cf.Config.db_name,'mongodb.host':cf.Config.host,'mongodb.is_reset':cf.Config.is_reset})

    print ("Initial a database")
    ####################################################

    print ("create default categories")
    for category in default_categories:
        category_tmp = models.Category.objects(name=category).first()
        if not category_tmp:
            category_tmp = models.Category()
            category_tmp.name = category
            category_tmp.save()
        else:
            print("The default categories is exist")

    ####################################################

    print("create CoE 2553 curriculum")
    coe_curriculum = models.Curriculum()
    # for key in curriculum_data.keys():
    coe_curriculum['faculty'] = curriculum_data['faculty']
    coe_curriculum['department'] = curriculum_data['department']
    coe_curriculum['year'] = curriculum_data['year']
    print("Add Studied Group")
    # coe_curriculum['studied_groups'].append('all')
    for studied_group in curriculum_data['studied_groups']:
        coe_curriculum['studied_groups'].append(studied_group)
    coe_curriculum.save()

    ####################################################
    #  print("Add Studied Group")

    # studied_group_tmp = models.StudiedGroup()
    # studied_group_tmp['name'] = 'all' # this is a general group
    # studied_group_tmp.save()
    # for studied_group in curriculum_data['studied_groups']:
    #     studied_group_tmp = models.StudiedGroup()
    #     studied_group_tmp['name'] = studied_group
    #     studied_group_tmp.save()

    ####################################################

    print("create subjects in CoE 2553 curriculum and relationship between subjects")
    for raw_subject in raw_subjects:

        subject_tmp = models.Subject()

        # add a simple data
        if 'code' in raw_subject: subject_tmp.code = raw_subject['code']
        subject_tmp.name = raw_subject['name']
        subject_tmp.credit = int(raw_subject.get('credit', '0'))
        # add curriculum
        subject_tmp.curriculum = coe_curriculum

        # add link to another object
        # add categories
        if 'categories' in raw_subject:
            for category in raw_subject['categories']:
                subject_tmp.categories.append(models.Category.objects(name=category).first())

        if 'studied_group' in raw_subject:
            subject_tmp.studied_group = raw_subject['studied_group']
        # else : subject_tmp.studied_group = 'all'

        if 'year' in raw_subject: subject_tmp.year = int(raw_subject.get('year', '0'))
        else :
            print(raw_subject['name'] +"doesn't have year")
        if 'semester' in raw_subject: subject_tmp.semester = int(raw_subject.get('semester', '0'))
        else :
            print(raw_subject['name'] +"doesn't have semester")
        subject_tmp.save()

    # link all prerequisite subject
    print("Link all prerequisite subject")
    for raw_subject in raw_subjects:

        if 'code' in raw_subject:
            subject_code = models.Subject.objects(code=raw_subject['code']).first()
        if 'studied_prerequisite' in raw_subject:
            for sp_code in raw_subject['studied_prerequisite']:
                subject_code.studied_prerequisite.append(models.Subject.objects(code=sp_code).first())
        if 'passed_prerequisite' in raw_subject:
            for pp_code in raw_subject['passed_prerequisite']:
                subject_code.passed_prerequisite.append(models.Subject.objects(code=pp_code).first())
        if 'corequisite' in raw_subject:
            for cr_code in raw_subject['corequisite']:
                subject_code.corequisite.append(models.Subject.objects(code=cr_code).first())
        if 'cocurrent' in raw_subject:
            for cc_code in raw_subject['cocurrent']:
                subject_code.corequisite.append(models.Subject.objects(code=cc_code).first())

        subject_code.save()

    ####################################################

    print("Adding grade")
    for grade in grade_info:
        grade_tmp = models.Grade(grade).save()

    ####################################################

    #initial test cases

    #add a member
    print("Add Thongdee Mana")
    member_thongdee = models.Member()
    member_thongdee.member_id = '5510110999'
    member_thongdee.name = 'Thongdee Mana'
    member_thongdee.curriculum = coe_curriculum
    member_thongdee.studied_group = 'first-group'
    member_thongdee.save()

    #add dummy data

    enrolled_lists_1_1 = [
        {'subject' : '200-101','grade' : 'C'},
        {'subject' : '242-101','grade' : 'C'},
        {'subject' : '322-101','grade' : 'W'},
        {'subject' : '332-103','grade' : 'C'},
        {'subject' : '332-113','grade' : 'C'},
        {'subject' : '640-101','grade' : 'C'},
        {'subject' : '890-101','grade' : 'C'}
    ]
    es_thongdee = models.EnrolledSubject()
