#!/usr/bin/env python
'''
initial_db
Description#   Initialize a database and test case
Developer#     Thada Wangthammang
'''
import os
import sys
import pymongo
import pprint

from r2als import models
from r2als import config as cf
from r2als.scripts import convert_curriculum as cc

default_categories = ['lecture', 'lab','project']
coe_curriculum_data = {
    'faculty': 'Engineering',
    'department': 'Computer Engineering',
    'year': 2553
}
# Not check key yet
raw_subjects = cc.CsvToModel().process('curriculum.csv')

pp = pprint.PrettyPrinter(indent=4)
# pp.pprint(raw_subjects )

if __name__ == '__main__':
    # if len(argv) != 2:
    #     usage(argv)
    # config_uri = argv[1]
    # setup_logging(config_uri)
    # settings = get_appsettings(config_uri)

    models.initial({'mongodb.db_name':cf.Config.db_name,'mongodb.host':cf.Config.host,'mongodb.is_reset':cf.Config.is_reset})

    print ("Initial a database")
    ####################################################

    print ("create default categories")
    for category in default_categories:
        category_tmp = models.Category.objects(name=category).first()
        if not category_tmp:
            category_tmp = models.Category()
            category_tmp.name = category
            category_tmp.save()
        else:
            print("The default categories is exist")

    ####################################################

    print("create CoE 2553 curriculum")
    coe_curriculum = models.Curriculum()
    for key in coe_curriculum_data.keys():
        coe_curriculum[key] = coe_curriculum_data[key]
    coe_curriculum.save()

    ####################################################

    print("create subjects in CoE 2553 curriculum and relationship between subjects")
    for raw_subject in raw_subjects:

        subject_tmp = models.Subject()

        # add a simple data
        subject_tmp.code = raw_subject['code']
        subject_tmp.name = raw_subject['name']
        try:
            subject_tmp.credit = int(raw_subject['credit'])
        except ValueError:
            print("Error in convert '"+raw_subject['credit']+"'")
            print("the credit is set to 0")
            subject_tmp.credit = 0
        # add curriculum
        subject_tmp.curriculum = coe_curriculum

        # add link to another object
        # add categories
        tmp_categories = raw_subject['categories'].split(':')
        for tmp_category in tmp_categories:
            print(raw_subject['name']+ " >> " +tmp_category)
            subject_tmp.categories.append(models.Category.objects(name=tmp_category).first())

        #


        subject_tmp.save()
    #initial test cases
