#!/usr/bin/env python
'''
initial_db
Description#   Initialize a database and test case
Developer#     Thada Wangthammang
'''
import os
import sys
import pymongo
import pprint

from r2als import models
from r2als import config as cf
from r2als.scripts import convert_curriculum as cc

default_categories = ['lecture', 'lab','project']
grade_info = [
    {'name': "A", 'score': 4.0, 'isCredit': True, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "B+", 'score': 3.5, 'isCredit': True, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "B", 'score': 3.0, 'isCredit': True, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "C+", 'score': 2.5, 'isCredit': True, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "C", 'score': 2.0, 'isCredit': True, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "D+", 'score': 1.5, 'isCredit': True, 'canReEnroll': True, 'isEnrolled': True},
    {'name': "D", 'score': 1.0, 'isCredit': True, 'canReEnroll': True, 'isEnrolled': True},
    {'name': "E", 'score': 0.0, 'isCredit': True, 'canReEnroll': True, 'isEnrolled': True},
    {'name': "S", 'isCredit': False, 'canReEnroll': True, 'isEnrolled': True},
    {'name': "U", 'isCredit': False, 'canReEnroll': False, 'isEnrolled': True},
    {'name': "W", 'isCredit': False, 'canReEnroll': False, 'isEnrolled': False}
]
# curriculum_data = {
#     'faculty': 'Engineering',
#     'department': 'Computer Engineering',
#     'year': 2553
# }

# Not check key yet
raw_curriculum = cc.CsvToModel().process('../data/coe_2553_curriculum.csv', True)
raw_subjects = raw_curriculum['subjects']
curriculum_data = raw_curriculum['info']

pp = pprint.PrettyPrinter(indent=4)
# pp.pprint(raw_subjects )

class PrepareInitSolution:

    member = None
    semesterItems = []
    curriculum = None
    def __init__(self, curriculum, member):
        self.member = member
        self.curriculum = curriculum
        # === Todo ===: Remove all his subject!

    def addStudiedSubject(self, year=1, semester=1, subjects=[]):
        # subjects example data:
        #   [ {'code' : '200-101','grade' : 'C'},
        #     {'code' : '242-101','grade' : 'C'} ]
        for subject in subjects:
            if 'code' not in subject or 'grade' not in subject:
                print("Error: subject list must have code & grade")
                exit()
        semesterItem = {}
        semesterItem['year'] = year
        semesterItem['semester'] = semester
        semesterItem['subjects'] = subjects
        self.semesterItems.append(semesterItem)

    def start(self):

        for semesterItem in self.semesterItems:

            mSemester = models.Semester()
            mSemester.member = self.member
            mSemester.year = semesterItem['year']
            mSemester.semester = semesterItem['semester']
            # Read all subject from same curriculum
            subjects = models.Subject.objects(curriculum = self.curriculum, year = semesterItem['year'], semester = semesterItem['semester'])
            for subject in subjects:
                if subject.studied_group == self.member.studied_group or subject.studied_group == "":
                    # print(subject.name + " "+ subject.studied_group+ " ==> "+ str(subject.year)+"/"+str(subject.semester))
                    gradeSubject = models.GradeSubject()
                    # If the subject is enrolled, loading it into GradeSubject object
                    for subjectSemester in semesterItem['subjects']:
                        if subject.code == subjectSemester['code']:
                            gradeSubject.grade = subjectSemester['grade']
                            break
                    gradeSubject.save()
                    mSemester.subjects.append(gradeSubject)
            mSemester.save()


if __name__ == '__main__':
    # if len(argv) != 2:
    #     usage(argv)
    # config_uri = argv[1]
    # setup_logging(config_uri)
    # settings = get_appsettings(config_uri)

    models.initial({'mongodb.db_name':cf.Config.db_name,'mongodb.host':cf.Config.host,'mongodb.is_reset':cf.Config.is_reset})

    print ("Initial a database")
    ####################################################

    print ("create default categories")
    for category in default_categories:
        category_tmp = models.Category.objects(name=category).first()
        if not category_tmp:
            category_tmp = models.Category()
            category_tmp.name = category
            category_tmp.save()
        else:
            print("The default categories is exist")

    ####################################################

    print("create CoE 2553 curriculum")
    coe_curriculum = models.Curriculum()
    # for key in curriculum_data.keys():
    coe_curriculum['faculty'] = curriculum_data['faculty']
    coe_curriculum['department'] = curriculum_data['department']
    coe_curriculum['year'] = curriculum_data['year']
    print("Add Studied Group")
    # coe_curriculum['studied_groups'].append('all')
    for studied_group in curriculum_data['studied_groups']:
        coe_curriculum['studied_groups'].append(studied_group)
    coe_curriculum.save()

    ####################################################
    #  print("Add Studied Group")

    # studied_group_tmp = models.StudiedGroup()
    # studied_group_tmp['name'] = 'all' # this is a general group
    # studied_group_tmp.save()
    # for studied_group in curriculum_data['studied_groups']:
    #     studied_group_tmp = models.StudiedGroup()
    #     studied_group_tmp['name'] = studied_group
    #     studied_group_tmp.save()

    ####################################################

    print("create subjects in CoE 2553 curriculum and relationship between subjects")
    # print(str(len(raw_subjects))+" subjects will be added!")
    for raw_subject in raw_subjects:

        subject_tmp = models.Subject()

        # add a simple data
        if 'code' in raw_subject:
            subject_tmp.isSpecific = True
            subject_tmp.code = raw_subject['code']
        else:
            subject_tmp.isSpecific = False
        subject_tmp.name = raw_subject['name']
        subject_tmp.credit = int(raw_subject.get('credit', '0'))
        # add curriculum
        subject_tmp.curriculum = coe_curriculum

        # add link to another object
        # add categories
        if 'categories' in raw_subject:
            for category in raw_subject['categories']:
                subject_tmp.categories.append(models.Category.objects(name=category).first())

        if 'studied_group' in raw_subject:
            subject_tmp.studied_group = raw_subject['studied_group']
        else : subject_tmp.studied_group = ''

        if 'year' in raw_subject: subject_tmp.year = int(raw_subject.get('year', '0'))
        else :
            print(raw_subject['name'] +"doesn't have year")
        if 'semester' in raw_subject: subject_tmp.semester = int(raw_subject.get('semester', '0'))
        else :
            print(raw_subject['name'] +"doesn't have semester")
        subject_tmp.save()

    # link all prerequisite subject
    print("Link all prerequisite subject")
    for raw_subject in raw_subjects:

        if 'code' in raw_subject:
            subject_code = models.Subject.objects(code=raw_subject['code']).first()

        if 'studied_prerequisite' in raw_subject:
            for sp_code in raw_subject['studied_prerequisite']:
                subject_code.studied_prerequisite.append(models.Subject.objects(code=sp_code).first())
        if 'passed_prerequisite' in raw_subject:
            for pp_code in raw_subject['passed_prerequisite']:
                subject_code.passed_prerequisite.append(models.Subject.objects(code=pp_code).first())
        if 'corequisite' in raw_subject:
            for cr_code in raw_subject['corequisite']:
                subject_code.corequisite.append(models.Subject.objects(code=cr_code).first())
        if 'cocurrent' in raw_subject:
            for cc_code in raw_subject['cocurrent']:
                subject_code.corequisite.append(models.Subject.objects(code=cc_code).first())


        subject_code.save()

    ####################################################

    print("Adding grade")
    for grade in grade_info:
        grade_tmp = models.Grade()
        # grade_tmp.name = grade['name']
        # if 'score' in grade:
        #     grade_tmp.score = grade['score']
        for key, value in grade.items():
            grade_tmp[key] = value
        grade_tmp.save()

    ####################################################

    #initial test cases

    #add a member
    print("Add Thongdee Mana")
    member_thongdee = models.Member()
    member_thongdee.member_id = '5710110999'
    member_thongdee.name = 'Thongdee Mana'
    member_thongdee.curriculum = coe_curriculum
    member_thongdee.studied_group = 'first-group'
    member_thongdee.registered_year = 2557
    member_thongdee.save()

    #add dummy data (thongdee)
    prepareInitSolution = PrepareInitSolution(coe_curriculum, member_thongdee)
    # year/semester: 1/1
    prepareInitSolution.addStudiedSubject(1,1,[
        {'code' : '200-101','grade' : 'C'},
        {'code' : '242-101','grade' : 'C'},
        {'code' : '322-101','grade' : 'W'},
        {'code' : '332-103','grade' : 'C'},
        {'code' : '332-113','grade' : 'C'},
        {'code' : '640-101','grade' : 'C'},
        {'code' : '890-101','grade' : 'C'}
    ])
    prepareInitSolution.addStudiedSubject(2,1,[
        {'code' : '242-205','grade' : 'C'}

    ])
    prepareInitSolution.start()
